onePatientTab <- f7Tab(
  tabName = 'Individual Risk',
  # icon = f7Icon('person_crop_circle'),
  icon = span(emo::ji('bust_in_silhouette'), class = 'my-icon'),
  active = TRUE,
  # p("This application helps you estimate individual risk of TBM, given a set of clinical and laboratory information.", 
  #   style = 'padding-left: 20px'),
  # p("You can choose to upload your database on calculate TBM risk case-wise. Please choose a mode below to get started.", 
  #   style = 'padding-left: 20px'),
  f7Flex(
    f7Block(
      f7BlockTitle('Patient profile'),
      shiny.fluent::Toggle.shinyInput(inputId = 'hiv',
                                      label = 'Is the patient tested positive with HIV or on Anti-retroviral therapy?',
                                      offText = 'Confirmed HIV negative',
                                      onText = 'Confirmed HIV positive'),
      shiny.fluent::Toggle.shinyInput(inputId = 'contact_tb',
                                      label = 'Any past noticeable contact with individual who was then diagnosed with TB in the past 12 months?',
                                      offText = 'No known contact',
                                      onText = 'Have known contact')
    ),
    f7Block(
      # f7Icon('person_crop_circle'),
      f7BlockTitle('Clinical Symptoms'),
      shiny.fluent::Toggle.shinyInput(inputId = 'tb_symptoms',
                                      label = 'Does the patient have either: weight loss, night sweating, or coughing > 2 weeks>?',
                                      offText = 'No',
                                      onText = 'Yes'),
      shiny.fluent::Toggle.shinyInput(inputId = 'focal_neuro_deficit',
                                      label = 'Does the patient have any focal neurological deficit?',
                                      offText = 'No',
                                      onText = 'Yes'),
      shiny.fluent::Toggle.shinyInput(inputId = 'cranial_nerve_palsy',
                                      label = 'Does the patient have any other cranial nerve palsy (expect for the focal neurological deficit)?',
                                      offText = 'No',
                                      onText = 'Yes'),
      shiny.fluent::Slider.shinyInput(inputId = 'gcs',
                                      label = 'Glasgow Coma Score',
                                      value = 15, min = 3, max = 15, step = 1),
      # misc$fluentNumericInput(inputId = 'gcs',
      #                         label = 'Glasgow Coma Score',
      #                         placeholder = '3-15',
      #                         warn.validator = 'x => x < 3 || x > 15 ? 2 : 0'),
      misc$fluentNumericInput(inputId = 'illness_day',
                              label = 'Days from first symptoms',
                              placeholder = '(days)',
                              description = 'Number of days from first symptoms to admission',
                              warn.validator = 'x => x > 30 ? 1 : 0')
    ),
    f7Block(
      f7BlockTitle('X-Ray Signs'),
      shiny.fluent::Toggle.shinyInput(inputId = 'xray_pul_tb',
                                      label = 'Pulmonary non-miliary TB'),
      shiny.fluent::Toggle.shinyInput(inputId = 'xray_mil_tb',
                                      label = 'Miliary TB'),
      div('Additional signs and symptoms', class = c("block-title", "medium"), style="margin-left:0"),
      f7BlockFooter('Required if no CSF biomarkers are provided'),
      shiny.fluent::Toggle.shinyInput(inputId = 'headache',
                                      label = 'Does the patient have headache?'),
      shiny.fluent::Toggle.shinyInput(inputId = 'psychosis',
                                      label = 'Does the patient have any psychosis symptoms'),
    ),
    f7Block(
      style='padding-top:10px',
      f7BlockTitle('Haematological tests'),
      f7BlockHeader('All features must be corrected for traumatic lumbar puncture'),
      misc$fluentNumericInput(inputId = 'csf_wbc',
                              label = 'CSF White cell count',
                              placeholder = '(cells/μL)',
                              warn.validator = 'x => parseInt(x) < parseInt(Shiny.shinyapp.$inputValues.csf_lym) ? 2 : x > 10000 ? 1 : 0'),
      misc$fluentNumericInput(inputId = 'csf_lym',
                              label = 'CSF Lymphocyte count',
                              placeholder = '(cells/μL)',
                              warn.validator = 'x => parseInt(x) > parseInt(Shiny.shinyapp.$inputValues.csf_wbc) ? 2 : x > 10000 ? 1 : 0'),
      misc$fluentNumericInput(inputId = 'csf_eos',
                              label = 'CSF Eosinophils count',
                              placeholder = '(cells/μL)',
                              warn.validator = 'x => parseInt(x) > parseInt(Shiny.shinyapp.$inputValues.csf_wbc) ? 2 : x > 1000 ? 1 : 0'),
      misc$fluentNumericInput(inputId = 'csf_rbc',
                              label = 'CSF Red Cell count',
                              placeholder = '(cells/μL)')
    ),
    f7Block(
      style='padding-top:10px',
      f7BlockTitle('Biochemical tests'),
      f7BlockHeader('All features must be corrected for traumatic lumbar puncture'),
      misc$fluentNumericInput(inputId = 'csf_glu',
                              label = 'CSF Glucose',
                              placeholder = '(mmol/L)',
                              warn.validator = 'x => x > 20 ? 2 : x > 10 ? 1 : 0'),
      misc$fluentNumericInput(inputId = 'bld_glu',
                              label = 'Paired Blood Glucose',
                              placeholder = '(mmol/L)',
                              warn.validator = 'x => x > 20 ? 2 : x > 10 ? 1 : 0'),
      misc$fluentNumericInput(inputId = 'csf_pro',
                              label = 'CSF Protein',
                              placeholder = '(g/L)',
                              warn.validator = 'x => x > 20 ? 2 : x > 10 ? 1 : 0'),
      misc$fluentNumericInput(inputId = 'csf_lac',
                              label = 'CSF Lactate',
                              placeholder = '(mmol/L)',
                              warn.validator = 'x => x > 20 ? 2 : x > 10 ? 1 : 0')
    ),
    f7Block(
      style='padding-top:10px',
      f7BlockTitle('Was the patient diagnosed with other?'),
      f7BlockFooter('(Most of the cases these are false, unless you are curious)'),
      shiny.fluent::Toggle.shinyInput(inputId = 'cryptococ',
                                      label = 'Cryptococcal Meningitis with Antigen or Indian Ink',
                                      onText = 'Yes',
                                      offText = 'No'),
      shiny.fluent::Toggle.shinyInput(inputId = 'gram',
                                      label = 'Other bacterial infection, with Gram stain',
                                      onText = 'Yes',
                                      offText = 'No'),
      f7BlockFooter('Model was not trained with yellow-flagged values and thus might not work correctly. Reg-flagged values are out of possible range and will be removed.')
    ),
    f7Block(), f7Block(shiny.fluent::PrimaryButton.shinyInput(inputId = 'submit_home', text = 'Submit'), class='float'),
  )
)

